version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: ./deps.sh
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/bower
        - tests/down/node_modules
        - node_modules
    - run: ./test.sh
workflows:
  version: 2
  build:
    jobs:
      - build
