name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MEDIASOUP_WORKER_PREBUILT_DOWNLOAD_BASE_URL: https://github.com/versatica/mediasoup/releases/download

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Set up environment
        run: |
          mkdir ../${{ github.sha }}
          
      - name: Install Meteor
        run: |
          curl "https://install.meteor.com/?release=2.9.1" | sh
          meteor --version

      - name: Install dependencies
        run: meteor npm install --production

      - name: Build app
        run: meteor build --directory ../${{ github.sha }}

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: jolly-roger.tar.gz
          path: ../${{ github.sha }}/jolly-roger.tar.gz
