name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MEDIASOUP_WORKER_PREBUILT_DOWNLOAD_BASE_URL: https://github.com/versatica/mediasoup/releases/download

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Set up environment
        run: |
          mkdir ../${{ github.sha }}
          mkdir ~/.ssh/
          printf %s "${{ secrets.JR_VPS_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
      - name: Install Meteor
        run: |
          curl "https://install.meteor.com/?release=2.9.1" | sh
          meteor --version

      - name: Install dependencies
        run: meteor npm install --production

      - name: Build app
        run: meteor build --directory ../${{ github.sha }}

      - name: Upload
        run: |
          scp ../${{ github.sha }}/jolly-roger.tar.gz ${{ secrets.JR_VPS_USERNAME }}@${{ secrets.JR_VPS_HOST }}:/home/jimsug/app -i ~/.ssh/deploy_key
      
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.JR_VPS_HOST }}
          username: ${{ secrets.JR_VPS_USERNAME }}
          key: ~/.ssh/deploy_key
          script: |
            cd /home/jimsug/app
            tar -xzf bundle.tar.gz
            sudo systemctl restart jolly-roger
